export enum Authority {

    //test chat
  TEST_CHAT = 'TEST.CHAT',

  //equipment
  EQUIPMENT_DELETE = 'EQUIPMENT.DELETE',
  EQUIPMENT_CREATE = 'EQUIPMENT.CREATE',
  EQUIPMENT_READ = 'EQUIPMENT.READ',
  EQUIPMENT_UPDATE = 'EQUIPMENT.UPDATE',

  //repair
  REPAIR_CREATE = 'REPAIR.CREATE',
  REPAIR_READ = 'REPAIR.READ',
  REPAIR_UPDATE = 'REPAIR.UPDATE',
  REPAIR_ACCEPT = 'REPAIR.ACCEPT',
  REPAIR_ACCEPTANCE_TESTING = 'REPAIR.ACCEPTANCE_TESTING',

  //maintenance
  MAINTENANCE_CREATE = 'MAINTENANCE.CREATE',
  MAINTENANCE_ACCEPT = 'MAINTENANCE.ACCEPT',
  MAINTENANCE_UPDATE = 'MAINTENANCE.UPDATE',
  MAINTENANCE_READ = 'MAINTENANCE.READ',

  //inspection
  INSPECTION_CREATE = 'INSPECTION.CREATE',
  INSPECTION_ACCEPT = 'INSPECTION.ACCEPT',
  INSPECTION_UPDATE = 'INSPECTION.UPDATE',
  INSPECTION_READ = 'INSPECTION.READ',

  //liquidation
  LIQUIDATION_READ = 'LIQUIDATION.READ',
  LIQUIDATION_CREATE = 'LIQUIDATION.CREATE',
  LIQUIDATION_ACCEPT = 'LIQUIDATION.ACCEPT',

  //handover
  HANDOVER_READ = 'HANDOVER.READ',
  HANDOVER_ACCEPT = 'HANDOVER.ACCEPT',
  HANDOVER_CREATE = 'HANDOVER.CREATE',

  //report broken
  REPORT_BROKEN_READ = 'REPORT_BROKEN.READ',
  REPORT_BROKEN_ACCEPT = 'REPORT_BROKEN.ACCEPT',
  REPORT_BROKEN_CREATE = 'REPORT_BROKEN.CREATE',

  //transfer
  TRANSFER_CREATE = 'TRANSFER.CREATE',
  TRANSFER_ACCEPT = 'TRANSFER.ACCEPT',
  TRANSFER_READ = 'TRANSFER.READ',

  //department
  DEPARTMENT_READ = 'DEPARTMENT.READ',
  DEPARTMENT_CREATE = 'DEPARTMENT.CREATE',
  DEPARTMENT_UPDATE = 'DEPARTMENT.UPDATE',
  DEPARTMENT_DELETE = 'DEPARTMENT.DELETE',

  //user
  USER_UPDATE = 'USER.UPDATE',
  USER_CREATE = 'USER.CREATE',
  USER_READ = 'USER.READ',
  USER_DELETE = 'USER.DELETE',

  //equipment group
  EQUIPMENT_GROUP_CREATE = 'EQUIPMENT_GROUP.CREATE',
  EQUIPMENT_GROUP_UPDATE = 'EQUIPMENT_GROUP.UPDATE',
  EQUIPMENT_GROUP_READ = 'EQUIPMENT_GROUP.READ',
  EQUIPMENT_GROUP_DELETE = 'EQUIPMENT_GROUP.DELETE',

  //equipment category
  EQUIPMENT_CATEGORY_CREATE = 'EQUIPMENT_CATEGORY.CREATE',
  EQUIPMENT_CATEGORY_UPDATE = 'EQUIPMENT_CATEGORY.UPDATE',
  EQUIPMENT_CATEGORY_READ = 'EQUIPMENT_CATEGORY.READ',
  EQUIPMENT_CATEGORY_DELETE = 'EQUIPMENT_CATEGORY.DELETE',

  //equipment unit
  EQUIPMENT_UNIT_CREATE = 'EQUIPMENT_UNIT.CREATE',
  EQUIPMENT_UNIT_UPDATE = 'EQUIPMENT_UNIT.UPDATE',
  EQUIPMENT_UNIT_READ = 'EQUIPMENT_UNIT.READ',
  EQUIPMENT_UNIT_DELETE = 'EQUIPMENT_UNIT.DELETE',

  //supply
  SUPPLY_CREATE = 'SUPPLY.CREATE',
  SUPPLY_UPDATE = 'SUPPLY.UPDATE',
  SUPPLY_READ = 'SUPPLY.READ',
  SUPPLY_DELETE = 'SUPPLY.DELETE',

  //supply unit
  SUPPLY_UNIT_CREATE = 'SUPPLY_UNIT.CREATE',
  SUPPLY_UNIT_UPDATE = 'SUPPLY_UNIT.UPDATE',
  SUPPLY_UNIT_READ = 'SUPPLY_UNIT.READ',
  SUPPLY_UNIT_DELETE = 'SUPPLY_UNIT.DELETE',

  //project
  PROJECT_CREATE = 'PROJECT.CREATE',
  PROJECT_UPDATE = 'PROJECT.UPDATE',
  PROJECT_READ = 'PROJECT.READ',
  PROJECT_DELETE = 'PROJECT.DELETE',
  ROLE_CREATE = 'ROLE.CREATE',
  ROLE_UPDATE = 'ROLE.UPDATE',
  ROLE_READ = 'ROLE.READ',
  ROLE_DELETE = 'ROLE.DELETE',

  //supplier
  SUPPLIER_CREATE = 'SUPPLIER.CREATE',
  SUPPLIER_UPDATE = 'SUPPLIER.UPDATE',
  SUPPLIER_READ = 'SUPPLIER.READ',
  SUPPLIER_DELETE = 'SUPPLIER.DELETE',

  //service
  SERVICE_CREATE = 'SERVICE.CREATE',
  SERVICE_UPDATE = 'SERVICE.UPDATE',
  SERVICE_READ = 'SERVICE.READ',
  SERVICE_DELETE = 'SERVICE.DELETE',

  //other roles...
  DDT = 'DDT',
  TK = 'TK',
  BGD = 'BGD',
  NVPVT = 'NVPVT',
  TPVT = 'TPVT',
  ROLE_ADMIN = 'ROLE_ADMIN',


  STATISTIC_EQUIPMENT = 'STATISTIC.EQUIPMENT',
  IMPORT_SUPPLIES = 'IMPORT.SUPPLIES',
  DASHBOARD_READ = 'DASHBOARD.READ',
  ROLE_TPVT = 'ROLE_TPVT',
};